### ISSUE TITLE
Bink_LED example

### ISSUE THREAD

**Issue by Serasidis** [Wiznet/W7500#5]
I saw that the Bink_LED example is not compiled in uVision.
Probably, the`uint8_t GPIO_ReadInputData(GPIO_TypeDef* GPIOx)` in to the W7500x_gpi.h file needs to be modified to `uint16_t GPIO_ReadInputData(GPIO_TypeDef* GPIOx)`

Please ignore the previous pull request I sent.

**Comment by irinakim12** [comment]
Sorry, we fixed the code,
thanks to Serasidis :+1:

**Comment by Serasidis** [comment]
Nice work guys :+1:
